#turtle's town
#to create houses
def house(color1,color2):
       t.pencolor("black")
       t.begin_fill()
       t.fillcolor(color1)
       for x in range(4):
              t.fd(100)
              t.left(90)
       t.end_fill()
       t.up()
       t.fd(100)
       t.down()
       t.pencolor("black")
       t.begin_fill()
       t.fillcolor(color2)
       t.left(45)
       t.forward(75)
       t.left(90)
       t.fd(75)
       t.end_fill()
       
# to create a tree
def tree(color1,color2):
       t.begin_fill()
       t.fillcolor(color1)
       t.fd(60)
       t.left(90)
       t.fd(100)
       t.left(90)
       t.fd(50)
       t.left(90)
       t.fd(100)
       t.end_fill()
       t.up()
       t.setheading(90)
       t.fd(100)
       t.left(90)
       t.fd(20)
       t.right(180)
       t.down()
       t.begin_fill()
       t.fillcolor(color2)
       t.fd(100)
       t.left(135)
       t.fd(70)  
       t.left(90)
       t.fd(70)
       t.up()
       t.setheading(90)
       t.fd(50)
       t.right(90)
       t.down()
       t.fd(100)
       t.left(135)
       t.fd(70)  
       t.left(90)
       t.fd(70)
       t.up()
       t.setheading(90)
       t.fd(50)
       t.right(90)
       t.down()
       t.fd(100)
       t.left(135)
       t.fd(70)  
       t.left(90)
       t.fd(70)
       t.end_fill()
       
# to create flowers
def flower(color1,color2,color3):
       t.color(color1)
       t.setheading(90)
       t.fd(30)
       t.right(45)
       t.fd(25)
       t.up()
       t.backward(25)
       t.left(45)
       t.down()
       t.fd(40)
       t.color(color2)
       t.begin_fill()
       t.fillcolor(color3)
       t.circle(20)
       t.end_fill()

       	   
import turtle
t=turtle.Turtle()
t.shape("turtle")
t.speed(5)
t.pensize(2)
w=turtle.Screen()
w.bgcolor("sky blue")
#to create road
t.begin_fill()
t.fillcolor("black")
t.forward(500)
t.up()
t.setheading(180)
t.down()
t.forward(1400)
t.left(90)
t.forward(100)
t.left(90)
t.forward(2000)
t.left(90)
t.forward(100)
t.end_fill()
t.up()
t.left(90)
t.forward(900)
t.left(90)
t.forward(50)
t.right(90)
t.down()
t.pensize(8)
t.pencolor("white")
t.forward(80)
t.up()
t.forward(80)
t.down()
t.fd(80)
t.up()
t.forward(80)
t.down()
t.fd(80)
t.up()
t.forward(80)
t.down()
t.fd(80)
#to place houses
t.up()
t.home()
t.left(90)
t.forward(200)
t.down()
house("white","yellow")
t.up()
t.right(45)
t.fd(100)
t.left(90)
t.fd(100)
t.right(180)
t.down()
house("blue","brown")
t.up()
t.left(135)
t.fd(500)
t.right(90)
t.fd(100)
t.left(180)
t.down()
house("red","green")
t.up()
t.setpos(100,-300)
t.setheading(90)
t.down()
house("pink","indigo")
t.up()
t.setpos(-100,-300)
t.setheading(90)
t.down()
house("cyan","brown")
t.up()
t.left(45)
t.forward(300)
t.left(90)
t.forward(200)
t.down()
#to make a waterhole
t.begin_fill()
t.fillcolor("blue")
t.up()
t.setpos(-300,-280)
t.down()
t.circle(100)
t.end_fill()
 
#to place tress
t.up()
t.forward(100)
tree("brown","green")
t.down()
t.up()
t.setheading(90)
t.forward(500)
t.right(90)
t.fd(400)
t.setheading(0)
tree("brown","red")  

#to place flowers
t.up()
t.setheading(270)
t.fd(170)
t.right(90)
t.fd(230)
t.down() 
flower("green","yellow","pink")
t.up()
t.home()
t.up()
t.goto(-150,200)
t.down()
flower("green","yellow","red")
t.up()
t.goto(250,-300)
t.down()
flower("green","yellow","blue")



